# Generated by Django 5.2.9 on 2025-12-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inbox', '0001_initial'),
        ('sends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='send',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_item', to='sends.send'),
        ),
    ]
